e = set()
a = input("enter the number: ")
e.add (int(a))
b = input("enter the number: ")
e.add (int(b))
c = input("enter the number: ")
e.add (int(c))
d = input("enter the number: ")
e.add (int(d))
x = input("enter the number: ")
e.add (int(x))
f = input("enter the number: ")
e.add (int(f))
g = input("enter the number: ")
e.add (int(g))
h = input("enter the number: ")
e.add (int(h))

print(e)
